### ISSUE TITLE
@nodoc to generated classes

### ISSUE THREAD

**Issue by YankoDiev-PrimeHolding** [Prime-Holding/RxBlocGenerator#21]
I want to have the {@nodoc} annotation comment before any class inside the generated BloC class
See the screenshot below:
![Screenshot 2020-07-23 at 11 45 15](https://user-images.githubusercontent.com/62933904/88267785-00686580-ccda-11ea-8631-9b7142ab54ea.png)

**Comment by DDavidPrime** [comment]
@YankoDiev-PrimeHolding Just for clarity, do you want it to be added for every generated class in general? Or do you want to have an annotation which will disable documentation (generate the ***nodoc***) for the annotated bloc ?

**Comment by YankoDiev-PrimeHolding** [comment]
Hi @DDavidPrime, as I know the generated classes are just those 2 the generated $Bloc and the BlocType. Let's ignore all generated from the runner classes in all *rxb.g.dart.
