### ISSUE TITLE
Enhance the error handling of RxBlocGenerator

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/RxBlocGenerator#6]

**Comment by DDavidPrime** [comment]
RxBlocGenerator:
[] General error handling
[] Bloc Events/States class missing

RxBlocEvent() annotation:
[] Error when no seed value is specified
[] Type mismatch between seed type and first parameter type should throw error

**Comment by YankoDiev-PrimeHolding** [comment]
All dart function declarations should be covered! Currently, I get an exception if I declare an event like this...
![image](https://user-images.githubusercontent.com/62933904/80375535-262fcb00-88a1-11ea-93c5-2cc35a2aa60b.png)
![image](https://user-images.githubusercontent.com/62933904/80375635-4d869800-88a1-11ea-81b6-dcfb9f3d4005.png)
The error message is "FN B isn't a valid override of FN A"

**Comment by YankoDiev-PrimeHolding** [comment]
![image](https://user-images.githubusercontent.com/62933904/80375984-d3a2de80-88a1-11ea-9ff7-20b3994246d8.png)
Optional parameters are not supported as well

**Comment by YankoDiev-PrimeHolding** [comment]
When we are solving the issues above please make sure that we also cover the default value option
Here it is an example...
![image](https://user-images.githubusercontent.com/62933904/80376290-4449fb00-88a2-11ea-843b-b1157c3e5e21.png)

**Comment by YankoDiev-PrimeHolding** [comment]
Parameters in events abstract class are not allowed
![image](https://user-images.githubusercontent.com/62933904/80457861-a35a4f00-8938-11ea-871e-7bd2eafbd06e.png)
I don't get any error when declaring a method with a body, should I?
![image](https://user-images.githubusercontent.com/62933904/80458295-3c896580-8939-11ea-9bab-a4cab6870347.png)

Return forms of getters shouldn't be allowed in states
![image](https://user-images.githubusercontent.com/62933904/80458024-def51900-8938-11ea-8f4d-bf377101613d.png)
Private events or states should show an error if possible
![image](https://user-images.githubusercontent.com/62933904/80456423-3940aa80-8936-11ea-9f95-ef1b997b596c.png)
Such self-wills shouldn't be allowed, should they?
![image](https://user-images.githubusercontent.com/62933904/80458541-9ee26600-8939-11ea-9afa-5ea9288d18b5.png)

**Comment by DDavidPrime** [comment]
Thanks @YankoDiev-PrimeHolding . Regarding your last comment, there should be an implementation of the abstract methods and getters for the states and events classes. Update your branch to cover the latest changes and let me know if the error still persists.
